### ISSUE TITLE
ruamel to ruamel_yaml

### ISSUE THREAD

**Issue by MFDESTINO** [codelv/enaml-native-cli#17]
Xubuntu 18.04 LTS
enaml-native-cli 2.2.4
conda 4.5.11

installed using [this guide](https://www.codelv.com/projects/enaml-native/docs/getting-started), but when I executed 
`enaml-native run-android` 

I got:

`Traceback (most recent call last):
  File "/home/daniel/miniconda3/bin/enaml-native", line 6, in <module>
    from enamlnativecli.main import main
  File "/home/daniel/miniconda3/lib/python3.6/site-packages/enamlnativecli/main.py", line 23, in <module>
    from ruamel import yaml
ModuleNotFoundError: No module named 'ruamel'
`

Tried using pip install to solve this, nothing worked, but when looking at `pip list` and `conda list` I realized that it was something with the name of the package, so I changed the line 23 from main.py:

`from ruamel import yaml`

to: 
`import ruamel_yaml as yaml`

and it worked

EDIT:
I also think maybe it's the same problem [here](https://github.com/codelv/enaml-native/issues/68)

**Comment by frmdstryr** [comment]
Thank you for reporting and looking at this. 

It looks like they have been making some breaking changes to their api 

https://yaml.readthedocs.io/en/latest/api.html

It would be nice to support both versions.

**Comment by frmdstryr** [comment]
Conda has a "patched" version of the package on their repo renamed to `ruamel_yaml`, so to support either version I've updated the code to handle this. 

Thank you!
