### ISSUE TITLE
Error: "Could not create a link to the env!"

### ISSUE THREAD

**Issue by null0nil** [codelv/enaml-native-cli#20]
Running "enaml-native create app" results in error:  "Could not create a link to the env!"

The problem occurs when there are spaces in app_name.   By default, app_name is "Hello World" and If I changed it to "helloworld", then I don't get this error.

**Comment by frmdstryr** [comment]
Thanks for reporting this.  https://github.com/codelv/enaml-native-cli/commit/3d4752bad56beea1a3c63addec890fee0d5f9531 should address the issue.

**Comment by shashi278** [comment]
I got the same issue while trying `enaml-native create app`.
Also, replacing spaces from the app name did not help. In fact I got the similar issue except the first line reading `OSError: symbolic link privilege not held`

Here's the error log:
https://gist.github.com/shashi278/d1d8f9bf6ae09abb41287ebe1ff6bca
