### ISSUE TITLE
codelv channel not found in anaconda?

### ISSUE THREAD

**Issue by rodgomesc** [codelv/enaml-native-cli#30]
it seems like `codelv` channel was deleted from anaconda? what i'm missing?

```sh
>> conda config --add channels codelv
>> conda install android-python

Collecting package metadata (current_repodata.json): failed
UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel codelv <https://conda.anaconda.org/codelv>
```

**Comment by frmdstryr** [comment]
Sorry yes the channel is gone (I self host my packages now). You can build/upload whatever you need from [conda-mobile](https://github.com/codelv/conda-mobile)

**Comment by rodgomesc** [comment]
thanks Jairus i'm closing this issue then, i'll send a pr later pointing to a updated repo
